services:
  db:
    image: postgres:16
    container_name: ecommerce_db
    environment:
      POSTGRES_USER: ecommerce_user
      POSTGRES_PASSWORD: 161901
      POSTGRES_DB: ecommerce_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: